
import type { Product, User, AiChat, Story, Category } from './types';

export const users: User[] = [
  {
    id: 'user1',
    username: 'maybeno',
    profilePictureUrl: 'https://firebasestorage.googleapis.com/v0/b/firebase-studio-demos.appspot.com/o/user-dalle.png?alt=media&token=ca334559-9ae6-4ca9-abb3-d3455a29b9b5',
    bio: 'AI ve modayı seviyorum. Trendleri keşfetmek için buradayım.',
    followerCount: 2,
    followingCount: 2,
    followingIds: ['user0', 'user2'],
    hasStory: true,
  },
  {
    id: 'user0',
    username: 'perisu',
    profilePictureUrl: 'https://placehold.co/100x100.png',
    followerCount: 1,
    followingCount: 1,
    followingIds: ['user1'],
    hasStory: true,
  },
  {
    id: 'user2',
    username: 'henife',
    profilePictureUrl: 'https://placehold.co/100x100.png',
    followerCount: 1,
    followingCount: 1,
    followingIds: ['user1'],
    hasStory: true,
  },
  { id: 'user3', username: 'ahmet', profilePictureUrl: 'https://placehold.co/100x100.png', followerCount: 0, followingCount: 0, hasStory: false },
  { id: 'user4', username: 'zeynep', profilePictureUrl: 'https://placehold.co/100x100.png', followerCount: 0, followingCount: 0, hasStory: false },
  { id: 'user5', username: 'mehmet', profilePictureUrl: 'https://placehold.co/100x100.png', followerCount: 0, followingCount: 0, hasStory: false },
  { id: 'user6', username: 'elif', profilePictureUrl: 'https://placehold.co/100x100.png', followerCount: 0, followingCount: 0, hasStory: false },
  { id: 'user7', username: 'can', profilePictureUrl: 'https://placehold.co/100x100.png', followerCount: 0, followingCount: 0, hasStory: false },
];

export const allUsers = users;

export const categories: Category[] = [
  { id: 'cat1', name: 'Giyim' },
  { id: 'cat2', name: 'Elektronik' },
  { id: 'cat3', name: 'Ev Dekorasyonu' },
  { id: 'cat4', name: 'Aksesuar' },
  { id: 'cat5', name: 'Ayakkabı' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'Klasik Mavi Kot Pantolon',
    description: 'Zamansız ve çok yönlü bu klasik mavi kot pantolon, gardırobun temel bir parçasıdır. Yüksek kaliteli denimden üretilmiştir, hem konfor hem de dayanıklılık sunar. Her mevsim ve her durum için mükemmeldir.',
    price: 89.99,
    imageUrls: ['https://placehold.co/600x800.png?text=Blue+Jeans', 'https://placehold.co/600x800.png?text=Denim+Style', 'https://placehold.co/600x800.png?text=Classic+Fit'],
    properties: { fabric: '%98 Pamuk, %2 Elastan', color: 'Klasik Mavi', size: 'W32/L32' },
    likeCount: 142,
    categoryId: 'cat1',
    stockQuantity: 67,
    aiSummary: 'Esnek kumaşı sayesinde gün boyu rahatlık sunar ve klasik kesimiyle her tarza uyum sağlar.',
    createdAt: new Date('2023-10-01T10:00:00Z').toISOString(),
  },
  {
    id: 'prod2',
    name: 'Yazlık Keten Gömlek',
    description: 'Bu hafif keten gömlek ile serin ve şık kalın. Nefes alabilen kumaşı, sıcak yaz günleri için idealdir ve rahat ama sofistike bir görünüm sağlar.',
    price: 74.50,
    imageUrls: ['https://placehold.co/600x800.png?text=Linen+Shirt', 'https://placehold.co/600x800.png?text=Summer+Style', 'https://placehold.co/600x800.png?text=Beige+Shirt'],
    properties: { fabric: '%100 Keten', color: 'Bej', size: 'Medium' },
    likeCount: 230,
    categoryId: 'cat1',
    stockQuantity: 85,
    aiSummary: 'Nefes alan keten kumaşı sayesinde bu gömlek, sıcak havalarda konforlu bir kullanım sunar ve ferah bir his verir.',
    createdAt: new Date('2023-11-15T12:30:00Z').toISOString(),
  },
  {
    id: 'prod3',
    name: 'Şehir Kaşifi Su Geçirmez Ceket',
    description: 'Şehir hayatı için tasarlanmış şık ve fonksiyonel bir ceket. Suya dayanıklı ve ceplerle dolu, şehir maceralarınız için mükemmel bir arkadaştır.',
    price: 149.00,
    imageUrls: ['https://placehold.co/600x800.png?text=Waterproof+Jacket', 'https://placehold.co/600x800.png?text=Urban+Explorer', 'https://placehold.co/600x800.png?text=Olive+Green+Jacket'],
    properties: { material: 'Sentetik Karışım', color: 'Zeytin Yeşili', size: 'Large' },
    likeCount: 380,
    categoryId: 'cat1',
    stockQuantity: 41,
    aiSummary: 'Suya dayanıklı yapısıyla beklenmedik hava koşullarına karşı koruma sağlar.',
    createdAt: new Date('2024-01-05T09:00:00Z').toISOString(),
  },
  {
    id: 'prod4',
    name: 'İpek Karışımlı Desenli Eşarp',
    description: 'Bu güzel ipek karışımlı eşarpla her kıyafete zarafet katın. Yumuşak, lüks ve çok yönlü, sayısız şekilde şekillendirilebilir.',
    price: 49.90,
    imageUrls: ['https://placehold.co/600x800.png?text=Silk+Scarf', 'https://placehold.co/600x800.png?text=Floral+Pattern', 'https://placehold.co/600x800.png?text=Elegant+Accessory'],
    properties: { fabric: '%50 İpek, %50 Modal', color: 'Çiçek Desenli' },
    likeCount: 95,
    categoryId: 'cat4',
    stockQuantity: 110,
    aiSummary: 'Yumuşak dokusu ve zarif deseniyle bu ipek karışımlı eşarp, her türlü kombine sofistike bir dokunuş katar.',
    createdAt: new Date('2024-02-20T18:45:00Z').toISOString(),
  },
  {
    id: 'prod5',
    name: 'Deri Sneaker Ayakkabı',
    description: 'Hem rahat hem de şık bu deri sneakerlar, günlük kullanım için mükemmel bir seçimdir. Kaliteli deriden yapılmış olup uzun ömürlü bir kullanım sunar.',
    price: 299.99,
    imageUrls: ['https://placehold.co/600x800.png?text=Leather+Sneakers', 'https://placehold.co/600x800.png?text=White+Shoes', 'https://placehold.co/600x800.png?text=Casual+Footwear'],
    properties: { material: 'Hakiki Deri', color: 'Beyaz', size: '42' },
    likeCount: 450,
    categoryId: 'cat5',
    stockQuantity: 60,
    aiSummary: 'Klasik beyaz tasarımı ile her kıyafetle kolayca kombinlenebilir, minimalist ve modern bir stil sunar.',
    createdAt: new Date('2024-03-10T11:20:00Z').toISOString(),
  },
  {
    id: 'prod6',
    name: 'Yüksek Belli Kargo Pantolon',
    description: 'Modern ve fonksiyonel bu kargo pantolon, rahat kesimi ve bol cepleriyle öne çıkıyor. Günlük kullanım için idealdir.',
    price: 129.90,
    imageUrls: ['https://placehold.co/600x800.png?text=Cargo+Pants', 'https://placehold.co/600x800.png?text=Khaki+Trousers', 'https://placehold.co/600x800.png?text=Utility+Style'],
    properties: { fabric: 'Pamuk', color: 'Haki', size: 'M' },
    likeCount: 180,
    categoryId: 'cat1',
    stockQuantity: 75,
    aiSummary: 'Bol cepleri ve rahat kesimiyle hem şık hem de pratik bir kullanım sunar.',
    createdAt: new Date('2024-04-12T14:00:00Z').toISOString(),
  },
  {
    id: 'prod7',
    name: 'Vintage Desenli Elbise',
    description: 'Geçmişin zarafetini günümüze taşıyan bu elbise, özel günleriniz için mükemmel bir seçim. Beli oturan kesimi ve uçuşan eteğiyle feminen bir görünüm sunar.',
    price: 249.99,
    imageUrls: ['https://placehold.co/600x800.png?text=Vintage+Dress', 'https://placehold.co/600x800.png?text=Red+Pattern', 'https://placehold.co/600x800.png?text=Retro+Fashion'],
    properties: { fabric: 'Viskon', color: 'Kırmızı Desenli', size: 'S' },
    likeCount: 312,
    categoryId: 'cat1',
    stockQuantity: 50,
    aiSummary: 'Göz alıcı deseni ve retro kesimiyle dikkat çeker, her ortamda şıklığınızı konuşturur.',
    createdAt: new Date('2024-05-01T09:30:00Z').toISOString(),
  },
  {
    id: 'prod8',
    name: 'Kapüşonlu Sweatshirt',
    description: 'Soğuk günler için ideal, yumuşak ve rahat bir sweatshirt. İçi polarlı yapısı sıcak tutarken, modern tasarımıyla şıklığınızdan ödün vermezsiniz.',
    price: 179.00,
    imageUrls: ['https://placehold.co/600x800.png?text=Hoodie', 'https://placehold.co/600x800.png?text=Gray+Sweatshirt', 'https://placehold.co/600x800.png?text=Comfy+Wear'],
    properties: { fabric: 'Pamuk & Polyester karışımı', color: 'Gri Melanj' },
    likeCount: 520,
    categoryId: 'cat1',
    stockQuantity: 90,
    aiSummary: 'Yumuşak iç dokusu ve ayarlanabilir kapüşonu ile maksimum konfor ve sıcaklık sağlar.',
    createdAt: new Date('2024-05-15T16:00:00Z').toISOString(),
  },
  {
    id: 'prod9',
    name: 'Deri Biker Ceket',
    description: 'Asi ve zamansız bir stilin anahtarı. Bu hakiki deri ceket, metal fermuar detayları ve klasik kesimiyle her kombine iddialı bir dokunuş katar.',
    price: 899.00,
    imageUrls: ['https://placehold.co/600x800.png?text=Biker+Jacket', 'https://placehold.co/600x800.png?text=Leather+Jacket', 'https://placehold.co/600x800.png?text=Black+Jacket'],
    properties: { material: 'Hakiki Deri', color: 'Siyah', size: 'L' },
    likeCount: 780,
    categoryId: 'cat1',
    stockQuantity: 25,
    aiSummary: 'Kaliteli derisi ve ikonik tasarımıyla yıllarca gardırobunuzun vazgeçilmezi olacak bir yatırım parçasıdır.',
    createdAt: new Date('2024-05-20T11:00:00Z').toISOString(),
  },
  {
    id: 'prod10',
    name: 'Ekose Gömlek',
    description: 'Klasik ekose deseniyle bu gömlek, hem günlük hem de şık kombinler için mükemmeldir. %100 pamuklu kumaşıyla rahatlık sunar.',
    price: 99.90,
    imageUrls: ['https://placehold.co/600x800.png?text=Plaid+Shirt', 'https://placehold.co/600x800.png?text=Flannel+Shirt', 'https://placehold.co/600x800.png?text=Casual+Shirt'],
    properties: { fabric: 'Pamuk', color: 'Kırmızı/Siyah Ekose', size: 'M' },
    likeCount: 250,
    categoryId: 'cat1',
    stockQuantity: 80,
    aiSummary: 'Bu çok yönlü ekose gömlek, kot pantolonlarla veya eteklerle kombinlenerek rahat bir stil yaratmanızı sağlar.',
    createdAt: new Date('2024-06-01T14:30:00Z').toISOString(),
  },
];

export const aiChats: AiChat[] = [
  {
    id: 'chat1',
    user: users.find(u => u.id === 'user1')!, 
    userComment: "Bu kot pantolonu yeni aldım ve harika! Süper rahat ve yaz için mükemmel. Yapay zeka mükemmel bedeni bulmama yardımcı oldu.",
    productSuggestions: [products[0]],
    likeCount: 15,
  },
  {
    id: 'chat2',
    user: users[2], // henife
    userComment: "Bu ceketi yapay zeka aramasıyla buldum ve şehir gezilerim için tam da ihtiyacım olan şeydi. Şık ve pratik!",
    productSuggestions: [products[2]],
    likeCount: 22,
  },
  {
    id: 'chat3',
    user: users[1], // perisu
    userComment: "Yapay zeka ile bu ipek eşarbı buldum, tam aradığım gibi!",
    productSuggestions: [products[3]],
    likeCount: 41,
  },
   {
    id: 'chat4',
    user: users[0], // perisu
    userComment: "Bugünün rahat ama havalı kombini! 😎 Bu ekose gömlek ve bol kot pantolon ikilisine bayıldım.",
    productSuggestions: [products[0], products[9]], 
    likeCount: 88,
  },
];

export const stories: Story[] = [
    { id: 'story1', userId: 'user1', imageUrl: 'https://placehold.co/1080x1920.png' },
    { id: 'story2', userId: 'user1', imageUrl: 'https://placehold.co/1080x1920.png' },
    { id: 'story3', userId: 'user0', imageUrl: 'https://placehold.co/1080x1920.png' },
    { id: 'story4', userId: 'user2', imageUrl: 'https://placehold.co/1080x1920.png' },
    { id: 'story5', userId: 'user2', imageUrl: 'https://placehold.co/1080x1920.png' },
    { id: 'story6', userId: 'user2', imageUrl: 'https://placehold.co/1080x1920.png' },
]

